### ISSUE TITLE
Add patch label function

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/spatial_warnings#1]

**Comment by fdschneider** [comment]
There is a function that counts patches and patch sizes called `patchsizedistr_ews()` but it uses 8-cell neighborhood for labelling via the function `SDMTools::ConnCompLabel()`. This should be replaced.

**Comment by ssumithra** [comment]
Should we close this issue?

**Comment by fdschneider** [comment]
Yes, redundant with #11.
