### ISSUE TITLE
 myfftshift_ews.R Matlab function

### ISSUE THREAD

**Issue by alaindanet** [fdschneider/spatial_warnings#16]
- Add documentation

This function is called in the case of spectral analysis, right ?

**Comment by fdschneider** [comment]
yes. I understand that it just shifts the matrix diagonally by 1/2. Right?

**Comment by alaindanet** [comment]
I took this from [matlab help](http://fr.mathworks.com/help/matlab/ref/fftshift.html):
Y = fftshift(X) rearranges the outputs of fft, fft2, and fftn by moving the zero-frequency component to the center of the array. It is useful for visualizing a Fourier transform with the zero-frequency component in the middle of the spectrum.

I understand that it puts the zero frequency in the middle of a vector or the center of a matrix

**Comment by guttal** [comment]
Yes, thats right! Should we close this issue?

**Comment by alexgenin** [comment]
Closing it !
