### ISSUE TITLE
Add patch size distribution fitting

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/spatial_warnings#2]
input should be a vector of patch sizes. 
returns a list of fitting results for all candidate distributions and a general summary of the best fitting function.  see issue fdschneider/caspr#2

**Comment by ssumithra** [comment]
You have a working function for fitting?

**Comment by fdschneider** [comment]
Working yes, but not for a binary matrix. Will update and commit it.

**Comment by fdschneider** [comment]
Done: b67194640a06d4390623f8ae0fac8a17eb051fa3  (see `?fitpsd` for info).

Please check and see if output is sufficient.

**Comment by fdschneider** [comment]
redundant with #15
