### ISSUE TITLE
Create as.binary_matrix.* functions (for input)

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/spatial_warnings#21]
The package needs to do its best try at converting data to binary matrices. The best way to do this I think is to create a `binary_matrix` class and `as.binary_matrix.*` S3 methods : 

 -  [x] `as.binary_matrix.data.frame`
 -  [x] `as.binary_matrix.matrix` (for non-binary matrices)
 -  [x] `as.binary_matrix.list` (for lists of stuff, determines what kind of objects the list is made of and apply the appropriate `as.*` function to them)
 -  [ ] `as.binary_matrix.ca_run` (not to be defined in this package but in caspr)
 -  [ ] ?

**Comment by fdschneider** [comment]
Does this make the `check_mat()` function obsolete? I think so, because you would just run `as.binary_matrix()` on any input for the indicator functions.

**Comment by alexgenin** [comment]
Right now `check_mat()` is used internally by the `as.binary_matrix.*` functions so it is still useful (maybe we can merge it in the same file ?). The calls within the indicator functions can be replaced by `as.binary_matrix()` though.

**Comment by alexgenin** [comment]
Very partially done in 01d532954576eb0b4562c37ad3bd3798859caba1, we probably want these functions to be more flexible and handle more cases (e.g. converting character/factor representation to binary in `as.binary_matrix.data.frame()`).

**Comment by alexgenin** [comment]
Done for all relevant datatypes not linked to caspr (89fb68b18dd5ea0d2ea575a80ac99b37b6bc3010).

**Comment by alexgenin** [comment]
I transfered the remaining method to caspr, closing now.
