### ISSUE TITLE
Generic SPEWS: Notes on testing for significance near the critical point

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/spatial_warnings#33]
For all of them we compute a null distribution of indicator values based on shuffled matrices, but the way we test against this distribution might have to differ from indicator to indicator: 

 * Moran's I should always be higher so we just do a one-tailed test for higher than expected values
 * Variance should always be higher in the coarse-grained observed data than in the coarsed-grained null dat (so one-tailed test too). However, the significance can decrease just before the tipping point (e.g. observed in Sabiha's runs for the pq model). 
 * Skewness can increase or decrease depending on whether the shift is upwards or downwards. In all cases, the *absolute value* of skewness should always increase before a critical point. This absolute value skewness is expected to be lower on a null coarsed-grain matrix (??) than observed.

**Comment by guttal** [comment]
Good points. More specifically, (a) I can not comment whether one-tailed distribution is better due to my lack of statistical knowledge. (b) Agreed - this happens because variance increases prior to transitions, hence variance of variance also increases. (c) Yes, the skewness of null coarse-grained matrix must be lower.

**Comment by SabihaMajumder** [comment]
There is an issue with calculating skewness in the package. For the matrix with all zeros, it divides the skewness by variance, which gives NaN. To avoid that, we can put an if condition, so that matrices with all zeros gives zero skewness

**Comment by alexgenin** [comment]
Done now
