### ISSUE TITLE
Add demo data

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/spatial_warnings#4]
There are a couple of data files in the original repo, but no documentation on how to interpret them. 

Could we add a couple of valid binary matrices as data objects that we can use for writing examples?

**Comment by fdschneider** [comment]
I added a matrix `B` and a list of matrices `L`. Due to lazy loading they have to be made available by calling `data(B)`.

Matrices of different sizes and types would be nice for testing.

**Comment by alaindanet** [comment]
We can also generate some matrix from caspr ? I can do it that if you think it's a good idea

**Comment by fdschneider** [comment]
I just generated some matrices with the models from caspr of different sizes in 50x50 and 200x200 landscapes. They are stored as .rda files within `/data` can be loaded by e.g. `data(B50m)` 

Those are rather random, but maybe at some point we could add data that show different patterns and indicators.
