### ISSUE TITLE
ForestGapModel 

### ISSUE THREAD

**Issue by ssumithra** [fdschneider/spatial_warnings#40]
1. Check 2d phase diagram axes as per example.R code. Are the axes swapped?
2.  Not all replicates for d values very close to transition in the continuous phase have non-zero densities. Patch Size distributions to be calculated only on the basis of finite density snapshots.

**Comment by alexgenin** [comment]
Regarding point 1., I just remade proper 2D diagrams for the manuscript (see issue #41). I think the axes are correct there, no ? (delta is spatial, d is non-spatial)

**Comment by alexgenin** [comment]
Obsolete
