### ISSUE TITLE
Coarse graining crashes R with subsize = 0

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/spatial_warnings#44]
Add a check in coarse_grain() to catch this ? (or maybe do it at higher level to avoid exceptions in highly-repeated code).

**Comment by SabihaMajumder** [comment]
In the coarse graining code , we take average over the submatrix which
includes dividing by the subsize. So you can not take subsize=0. If you
want no coarse graining , take subsize =1.

**Comment by alexgenin** [comment]
Fixed in 8d46593dd9599de1c70c4433813c1287c7c99e7c
