### ISSUE TITLE
define R package structure

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/spatial_warnings#5]
We need to wrap this into a valid R package. 

The globally accepted input should be a binary matrix, `A`. 
- Any factorial matrix `F` with the focal state "+" can be easily converted into such by `A <- F == "+"  `. 
- Same works for integer matrices, `I`. `A <- I == 1`

Many of the present functions can be run on that directly. Others need patch counts. Thus a core function `label()`should provide a fast labelling of patches and return a matrix with integer patch IDs.
 
Then a secondary function could take in the binary matrix as input and return a vector of patch sizes and/or a table of cumulative patch sizes.

**Comment by alexgenin** [comment]
Following our discussion, I suggest the following plan/structure/code organization : 

All indicator functions could accept a binary matrix as first argument, but are free to return any object (numeric vectors and matrices are encouraged). They should go by the name of indicator_\<name\>. For example, *indicator_variance* would have the following structure: 

```r
indicator_variance <- function(mat) {
  check_mat(mat) # sanity checks for the passed matrix
  if (is.list(mat)) { 
    return( lapply(mat, indicator_variance) )
  }
  
  <actual computation of the indicator>
  
  return(result) # any object, in this case a vector of length 1.
}
```

(note that we could also implement this using [closures](http://adv-r.had.co.nz/Functional-programming.html#closures) to avoid code duplication. It would be pretty elegant but I feel this adds a bit of complexity).

A "meta" fuction indicator_all then follows the same structure but returns a list with all the objects returned by the indicator functions. This way one can either use a single indicator alone or have a general picture of all indicators.

Some indicators require a transformation of the matrix first: this work should be externalized in other functions. To avoid recomputing unnecesary intermediate results, one should be able to pass them as optional arguments, e.g. for the maximum patch size distribution:

```r
indicator_maxpatchsize <- function(mat = NULL, patch_size_distr = psdistr(mat) ) {
  check_mat(mat) # sanity checks for the passed matrix (no error if NULL)
  if ( ! is.null(mat) && is.list(mat)) { # FALSE for mat = NULL
    return( lapply(mat, indicator_maxpatchsize) )
  }
  
  return( max(patch_size_distr) )  
}
```
This way if one only has the matrix, then the intermediate results are recomputed, otherwise just the latter is used.

**Comment by fdschneider** [comment]
Good. I don't think closures are necessary, although it's a nice concept that I completely forgot about. 

Defining recursive functions inside a function is quite efficient, too. It can be combined with checking for valid input. Also, `match.arg()` can be useful here. 

```
indicator_sd <- function(A) {

# if list, apply the indicator function to all matrices within the list
if("list" %in% class(A)) lapply(A, indicator_x)  
# if numeric, stop
if("numeric" %in% class(A) ) stop("argument must be a binary matrix!")

sd(A)
}

```

Since this repeats in several of our functions, we might wrap that checking into a seperate validation function.

**Comment by fdschneider** [comment]
I checked the functions currently present in this repo and I think there is quite some work to do. So far, this is what we have: 

The package contains three different kinds of functions:

- **pre-processing functions**: returning some required input for further indicator calculation.
- **indicator functions**: returning an indicator value or values for the given matrix.
- a **report function**: running all indicators on  a given matrix or list of matrices and returns a visual on-screen report. 

The input for all functions is a binary matrix (or a list of binary matrices) of squared dimensions. 

## pre-processing functions

- `lbl()` : labels all unique patches 
- `caspr::patches()`: returns a vector of patch sizes (needs to be translated for binary matrices)
- `patchsizedistr_ews()` or `psd()`: returns a table of cumulative patch sizes, i.e. the number and proportion of patches larger than each unique patch size. 
- `myfftshift()` : shifts the matrix diagonally by 1/2 
- `reducedmatrix_ews()` : coarse-grains the binary matrix into a matrix of numerical values

## indicator functions

- `rspec()` : r-sepctrum and theta-spectrum (uses `myfftshift()` and `stats::fft()`)
- `indicator_moran()` or `morancorrelation_ews()`: returns Morran's I 
- `corrfunc()` : returns spatial correlation
- `fitpsd()` : returns and compares alternative model fits for cumulative patch size distributions (uses input from `psd()`)
- `fracgeo()` : returns fractal geometry of the lattice, i.e. the average perimeter to area ratio. 

## report function

- `spatial_ews_main()` or `spatial_ews()` : compiles a report of spatial indicators for each given lattice. 

There are some wrapper functions that take a binary matrix and apply some indicators. There are a couple of functions that are partly redundant. I am not sure where the `reducedmatrix_ews()` is going to be used. 
Referring to the list in the [wiki](https://github.com/fdschneider/spatial_warnings/wiki), the features are quite complete, but the gears are not in place at all. We are going to rename almost all of those functions into a unified naming scheme. 

I think we need a flow chart that describes which function does what. I will try to provide that by tomorrow. It would be much easier if we had a complete list of indicators. Maybe the experts on  spatial indicators could add a little bit of input to the wiki to provide the big picture.

**Comment by alexgenin** [comment]
Thanks for the summary. I see there are mentions of detrending in some functions (e.g. indicator_skewness_main). I guess we need a *detrend()* preprocessing function that does this job.

**Comment by alaindanet** [comment]
Thank you Flo. I am currently completing the README file with the name of the functions and on which functions they depend, what they do, etc....

**Comment by fdschneider** [comment]
I close this since its mostly obsolete after refining the package structure today (#19).
