### ISSUE TITLE
Morans' I (spatial autocorrelation)

### ISSUE THREAD

**Issue by alaindanet** [fdschneider/spatial_warnings#8]
- Find publication of the index. I have already the paper of Moran (1950) but it's quite hard to read. There are others publications on this index.

- Change the structure of the fonction in the standard way as it was proposed by [Alex](https://github.com/fdschneider/spatial_warnings/issues/6).

- Add the documentation

**Comment by alaindanet** [comment]
I changed the structure of the function and add a first documentation.

I found some formulations of the Moran's I but all of them are differents of the formulation in the function provived [here](https://github.com/fdschneider/spatial_warnings/blob/master/R/morancorrelation_ews.R).

Somebody knows from which paper this function was defined ?

**Comment by alexgenin** [comment]
Working on it

**Comment by alexgenin** [comment]
I added ./R/indicator_moran.R but I saw in the meantime that some other similar functions (./R/indicator_MoranCor*) popped out so there might be duplicates.

**Comment by alaindanet** [comment]
Okay, I think there was a mismatch between you and @SabihaMajumder .
May be we can merge them.

**Comment by SabihaMajumder** [comment]
May be we can compare the both and merge.

**Comment by alaindanet** [comment]
Sabiha created two scripts: one with the core function and one which checks the matrix and computes the indicators by calling the core function.
May be can merge them in one file.

**Comment by alaindanet** [comment]
I just create a new script which has may be a more clear structure. [Link](https://github.com/fdschneider/spatial_warnings/blob/master/R/indicator_moran_test.R).

There is still several issues in my opinion that I want to share:
 
- The `DISCRETE` option seems unnecessary if we want the output of the index both for unreduce and reduced matrices.

- The null model is currently based on one random matrix. I think that we should at least compute the null parameters on one hundred random matrix to be able to discrimate data vs null model.

**Comment by alaindanet** [comment]
Demo added in draft and few test implemented.

**Comment by alexgenin** [comment]
OK, I'm working on merging the files so we can close this issue. 

Hey Alain, have you pushed your tests ? It seems that ./tests/testthat/test-moran.R is empty.

**Comment by alexgenin** [comment]
I merged everything in `./R/indicator_moran.R`, mostly based on Alain's version. I also updated the draft file. See 7662062cdcca1423ce2c0c6f15eb6048d0583baa.

I agree with computing a null distribution and testing against it. I will implement it tomorrow if nobody is working on it, so we can close this issue.

**Comment by alaindanet** [comment]
I didn't create test file, thank you for the merge!
For the null distribution, it would be great to have an option to set up 
the number of replication.

A max number of replication seems hard to define. Usually, I use 
combination calculation to set up the maximum number of randomization 
that I can do for my data.
But here, as the order of the cells matter, we deal with permutation, so 
the number of max replication becomes huge (n!, for exemple for 10 
cells: 3 millions possible permutations)

The problem is that you will always find that your index is superior to 
the 95 percentiles of your null distribution because you will increase 
your replications until you reach it.

But finally, it's not our problem.

Thank you Alex for the merge!


On 16/07/2015 18:43, Alex Genin wrote:
>
> I merged everything in |./R/indicator_moran.R|, mostly based on 
> Alain's version. I also updated the draft file. See 7662062 
> <https://github.com/fdschneider/spatial_warnings/commit/7662062cdcca1423ce2c0c6f15eb6048d0583baa>.
>
> I agree with computing a null distribution and testing against it. I 
> will implement it tomorrow if nobody is working on it, so we can close 
> this issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fdschneider/spatial_warnings/issues/8#issuecomment-122016283>.
>

-- 
Alain Danet
PhD student in Ecology
Biodicée Lab
University of Montpellier

**Comment by alexgenin** [comment]
Ha, our messages crossed.

OK, this should be good now. I'm not closing the issue in case something arises though. There is (of course :) ) an option to set the number of replicates. I don't know the ideal number, so I set it to 499 for a reasonable computing time (we can't explore the full space of course).

As for the `DISCRETE` option (from a past message), I feel it should be up to the calling function (or the user) to know what it/he wants. 

It would be nice also if the variance/skewness indicators follow the same naming in output so the user is not confused.

**Comment by alaindanet** [comment]
Yes, I aggree for variance/skewness indicator.
Yes, there will be not an ideal number because of the number of possible permutation.

One more thing before to close the issue, we still haven't got the reference for this formula.

@SabihaMajumder have suggested Guttal et al. (2008) if I remember well.

**Comment by alexgenin** [comment]
OK, I close this issue now as the problem seems solved.
